################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Application/STM32N6570-DK/Src/app_camerapipeline.c \
C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Application/STM32N6570-DK/Src/app_fuseprogramming.c \
C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Middlewares/ai-postprocessing-wrapper/app_postprocess_fd_blazeface_ui.c \
C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Middlewares/ai-postprocessing-wrapper/app_postprocess_fd_yunet_ui.c \
C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Application/STM32N6570-DK/Src/crop_img.c \
C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Application/STM32N6570-DK/Src/main.c \
C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx/mcu_cache.c \
C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Model/STM32N6570-DK/network.c \
C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx/npu_cache.c \
C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Model/STM32N6570-DK/stai_network.c \
C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Application/STM32N6570-DK/Src/stm32_lcd_ex.c \
C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Application/STM32N6570-DK/Src/stm32n6xx_it.c \
C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Application/STM32N6570-DK/Src/syscalls.c 

OBJS += \
./Application/app_camerapipeline.o \
./Application/app_fuseprogramming.o \
./Application/app_postprocess_fd_blazeface_ui.o \
./Application/app_postprocess_fd_yunet_ui.o \
./Application/crop_img.o \
./Application/main.o \
./Application/mcu_cache.o \
./Application/network.o \
./Application/npu_cache.o \
./Application/stai_network.o \
./Application/stm32_lcd_ex.o \
./Application/stm32n6xx_it.o \
./Application/syscalls.o 

C_DEPS += \
./Application/app_camerapipeline.d \
./Application/app_fuseprogramming.d \
./Application/app_postprocess_fd_blazeface_ui.d \
./Application/app_postprocess_fd_yunet_ui.d \
./Application/crop_img.d \
./Application/main.d \
./Application/mcu_cache.d \
./Application/network.d \
./Application/npu_cache.d \
./Application/stai_network.d \
./Application/stm32_lcd_ex.d \
./Application/stm32n6xx_it.d \
./Application/syscalls.d 


# Each subdirectory must supply rules for building sources it contributes
Application/app_camerapipeline.o: C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Application/STM32N6570-DK/Src/app_camerapipeline.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx '-DECBLOB_CONST_SECTION=__attribute__((section(".flash_blob")))' '-DPOSTPROCESS_WRAPPER_SECTION=__attribute__((section(".psram_bss")))' -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/STM32N6570-DK -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/imx335 -I../../../../Middlewares/stm32-mw-camera/sensors/vd6g -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -I../../../../Middlewares/stm32-mw-camera/sensors/vd1943 -I../../../../Middlewares/stm32-mw-camera/sensors/ov5640 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/app_fuseprogramming.o: C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Application/STM32N6570-DK/Src/app_fuseprogramming.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx '-DECBLOB_CONST_SECTION=__attribute__((section(".flash_blob")))' '-DPOSTPROCESS_WRAPPER_SECTION=__attribute__((section(".psram_bss")))' -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/STM32N6570-DK -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/imx335 -I../../../../Middlewares/stm32-mw-camera/sensors/vd6g -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -I../../../../Middlewares/stm32-mw-camera/sensors/vd1943 -I../../../../Middlewares/stm32-mw-camera/sensors/ov5640 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/app_postprocess_fd_blazeface_ui.o: C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Middlewares/ai-postprocessing-wrapper/app_postprocess_fd_blazeface_ui.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx '-DECBLOB_CONST_SECTION=__attribute__((section(".flash_blob")))' '-DPOSTPROCESS_WRAPPER_SECTION=__attribute__((section(".psram_bss")))' -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/STM32N6570-DK -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/imx335 -I../../../../Middlewares/stm32-mw-camera/sensors/vd6g -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -I../../../../Middlewares/stm32-mw-camera/sensors/vd1943 -I../../../../Middlewares/stm32-mw-camera/sensors/ov5640 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/app_postprocess_fd_yunet_ui.o: C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Middlewares/ai-postprocessing-wrapper/app_postprocess_fd_yunet_ui.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx '-DECBLOB_CONST_SECTION=__attribute__((section(".flash_blob")))' '-DPOSTPROCESS_WRAPPER_SECTION=__attribute__((section(".psram_bss")))' -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/STM32N6570-DK -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/imx335 -I../../../../Middlewares/stm32-mw-camera/sensors/vd6g -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -I../../../../Middlewares/stm32-mw-camera/sensors/vd1943 -I../../../../Middlewares/stm32-mw-camera/sensors/ov5640 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/crop_img.o: C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Application/STM32N6570-DK/Src/crop_img.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx '-DECBLOB_CONST_SECTION=__attribute__((section(".flash_blob")))' '-DPOSTPROCESS_WRAPPER_SECTION=__attribute__((section(".psram_bss")))' -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/STM32N6570-DK -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/imx335 -I../../../../Middlewares/stm32-mw-camera/sensors/vd6g -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -I../../../../Middlewares/stm32-mw-camera/sensors/vd1943 -I../../../../Middlewares/stm32-mw-camera/sensors/ov5640 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/main.o: C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Application/STM32N6570-DK/Src/main.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx '-DECBLOB_CONST_SECTION=__attribute__((section(".flash_blob")))' '-DPOSTPROCESS_WRAPPER_SECTION=__attribute__((section(".psram_bss")))' -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/STM32N6570-DK -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/imx335 -I../../../../Middlewares/stm32-mw-camera/sensors/vd6g -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -I../../../../Middlewares/stm32-mw-camera/sensors/vd1943 -I../../../../Middlewares/stm32-mw-camera/sensors/ov5640 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/mcu_cache.o: C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx/mcu_cache.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx '-DECBLOB_CONST_SECTION=__attribute__((section(".flash_blob")))' '-DPOSTPROCESS_WRAPPER_SECTION=__attribute__((section(".psram_bss")))' -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/STM32N6570-DK -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/imx335 -I../../../../Middlewares/stm32-mw-camera/sensors/vd6g -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -I../../../../Middlewares/stm32-mw-camera/sensors/vd1943 -I../../../../Middlewares/stm32-mw-camera/sensors/ov5640 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/network.o: C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Model/STM32N6570-DK/network.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx '-DECBLOB_CONST_SECTION=__attribute__((section(".flash_blob")))' '-DPOSTPROCESS_WRAPPER_SECTION=__attribute__((section(".psram_bss")))' -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/STM32N6570-DK -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/imx335 -I../../../../Middlewares/stm32-mw-camera/sensors/vd6g -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -I../../../../Middlewares/stm32-mw-camera/sensors/vd1943 -I../../../../Middlewares/stm32-mw-camera/sensors/ov5640 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/npu_cache.o: C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx/npu_cache.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx '-DECBLOB_CONST_SECTION=__attribute__((section(".flash_blob")))' '-DPOSTPROCESS_WRAPPER_SECTION=__attribute__((section(".psram_bss")))' -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/STM32N6570-DK -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/imx335 -I../../../../Middlewares/stm32-mw-camera/sensors/vd6g -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -I../../../../Middlewares/stm32-mw-camera/sensors/vd1943 -I../../../../Middlewares/stm32-mw-camera/sensors/ov5640 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/stai_network.o: C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Model/STM32N6570-DK/stai_network.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx '-DECBLOB_CONST_SECTION=__attribute__((section(".flash_blob")))' '-DPOSTPROCESS_WRAPPER_SECTION=__attribute__((section(".psram_bss")))' -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/STM32N6570-DK -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/imx335 -I../../../../Middlewares/stm32-mw-camera/sensors/vd6g -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -I../../../../Middlewares/stm32-mw-camera/sensors/vd1943 -I../../../../Middlewares/stm32-mw-camera/sensors/ov5640 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/stm32_lcd_ex.o: C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Application/STM32N6570-DK/Src/stm32_lcd_ex.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx '-DECBLOB_CONST_SECTION=__attribute__((section(".flash_blob")))' '-DPOSTPROCESS_WRAPPER_SECTION=__attribute__((section(".psram_bss")))' -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/STM32N6570-DK -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/imx335 -I../../../../Middlewares/stm32-mw-camera/sensors/vd6g -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -I../../../../Middlewares/stm32-mw-camera/sensors/vd1943 -I../../../../Middlewares/stm32-mw-camera/sensors/ov5640 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/stm32n6xx_it.o: C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Application/STM32N6570-DK/Src/stm32n6xx_it.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx '-DECBLOB_CONST_SECTION=__attribute__((section(".flash_blob")))' '-DPOSTPROCESS_WRAPPER_SECTION=__attribute__((section(".psram_bss")))' -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/STM32N6570-DK -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/imx335 -I../../../../Middlewares/stm32-mw-camera/sensors/vd6g -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -I../../../../Middlewares/stm32-mw-camera/sensors/vd1943 -I../../../../Middlewares/stm32-mw-camera/sensors/ov5640 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/syscalls.o: C:/FD/stm32ai-modelzoo-services/application_code/face_detection/STM32N6/Application/STM32N6570-DK/Src/syscalls.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx '-DECBLOB_CONST_SECTION=__attribute__((section(".flash_blob")))' '-DPOSTPROCESS_WRAPPER_SECTION=__attribute__((section(".psram_bss")))' -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/STM32N6570-DK -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/imx335 -I../../../../Middlewares/stm32-mw-camera/sensors/vd6g -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -I../../../../Middlewares/stm32-mw-camera/sensors/vd1943 -I../../../../Middlewares/stm32-mw-camera/sensors/ov5640 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Application

clean-Application:
	-$(RM) ./Application/app_camerapipeline.cyclo ./Application/app_camerapipeline.d ./Application/app_camerapipeline.o ./Application/app_camerapipeline.su ./Application/app_fuseprogramming.cyclo ./Application/app_fuseprogramming.d ./Application/app_fuseprogramming.o ./Application/app_fuseprogramming.su ./Application/app_postprocess_fd_blazeface_ui.cyclo ./Application/app_postprocess_fd_blazeface_ui.d ./Application/app_postprocess_fd_blazeface_ui.o ./Application/app_postprocess_fd_blazeface_ui.su ./Application/app_postprocess_fd_yunet_ui.cyclo ./Application/app_postprocess_fd_yunet_ui.d ./Application/app_postprocess_fd_yunet_ui.o ./Application/app_postprocess_fd_yunet_ui.su ./Application/crop_img.cyclo ./Application/crop_img.d ./Application/crop_img.o ./Application/crop_img.su ./Application/main.cyclo ./Application/main.d ./Application/main.o ./Application/main.su ./Application/mcu_cache.cyclo ./Application/mcu_cache.d ./Application/mcu_cache.o ./Application/mcu_cache.su ./Application/network.cyclo ./Application/network.d ./Application/network.o ./Application/network.su ./Application/npu_cache.cyclo ./Application/npu_cache.d ./Application/npu_cache.o ./Application/npu_cache.su ./Application/stai_network.cyclo ./Application/stai_network.d ./Application/stai_network.o ./Application/stai_network.su ./Application/stm32_lcd_ex.cyclo ./Application/stm32_lcd_ex.d ./Application/stm32_lcd_ex.o ./Application/stm32_lcd_ex.su ./Application/stm32n6xx_it.cyclo ./Application/stm32n6xx_it.d ./Application/stm32n6xx_it.o ./Application/stm32n6xx_it.su ./Application/syscalls.cyclo ./Application/syscalls.d ./Application/syscalls.o ./Application/syscalls.su

.PHONY: clean-Application

